# Generated by Django 2.2.4 on 2020-05-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0003_auto_20200506_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='stripecustomer',
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
