# Generated by Django 2.2.4 on 2020-05-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0006_customer_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
