# Generated by Django 2.2.4 on 2020-05-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0008_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='new_customer',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='Billing.Customer'),
        ),
    ]
