# Generated by Django 2.2.4 on 2020-05-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0009_billingprofile_new_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='new_customer',
            field=models.ForeignKey(default=False, on_delete='CASCADE', to='Billing.Customer'),
        ),
    ]
