# Generated by Django 2.2.4 on 2020-05-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0010_auto_20200512_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='new_customer',
        ),
    ]
