# Generated by Django 2.2.4 on 2020-05-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0012_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=120, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('outcome', models.TextField(blank=True, max_length=20, null=True)),
                ('outcome_type', models.CharField(blank=True, max_length=20, null=True)),
                ('seller_message', models.CharField(blank=True, max_length=20, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_profile', models.ForeignKey(on_delete='CASCADE', to='Billing.BillingProfile')),
            ],
        ),
    ]
