# Generated by Django 2.2.4 on 2020-05-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
