# Generated by Django 2.2.4 on 2020-06-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200531_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pharmacy_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('comment', models.CharField(max_length=120)),
            ],
        ),
    ]
