# Generated by Django 2.2.4 on 2020-06-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200608_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment',
            field=models.TextField(max_length=120),
        ),
    ]
